[project]
name = "conv-halide"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "halide>=19.0.0",
    "numpy>=2.0.2",
    "torch>=2.7.1",
]
